### PR TITLE
fix(ci): Test osx using travis ci 

### PR DESCRIPTION
**Pull request by riddell-stan**
Needs to be rebased after #201 is merged.

### CODE REVIEW

**Comment by riddell-stan** [comment]
Getting a "Fatal Python error: Bus error" with xcode 9. I'll see if it happens with xcode 10.

**Comment by ahartikainen** [comment]
It is something to do with threading?

**Comment by riddell-stan** [comment]
No threads are used. STAN_THREADS is not defined and we use processor-based parallelism.

**Comment by ahartikainen** [comment]
```
httpstan/lib/stan/lib/stan_math/lib/boost_1.69.0/boost/type_traits/detail/has_binary_operator.hpp:54:156: error: no template named 'declval' in namespace 'std'; did you mean simply 'declval'?
```

This is `libc++ vs `libstd++` problem we have had before.

**Comment by ahartikainen** [comment]
Would 10.4 work?

https://docs.travis-ci.com/user/languages/c/#c11c11-and-beyond-and-toolchain-versioning

**Comment by riddell-stan** [comment]
Well, we gained Windows, lost mac, and lost gcc on Linux. Not a total loss. :)

**Pull request closed without merging**
