### PR TITLE
CI: test on Windows (MSVC)

### PR DESCRIPTION
**Pull request by riddell-stan**

### CODE REVIEW

**Comment by riddell-stan** [comment]
This hits an error (MSVC?):
```
httpstan/lib/stan/lib/stan_math/lib/boost_1.66.0\boost/spirit/home/qi/operator/sequence_base.hpp(59): error C3203: 'type': unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type
```

**Comment by ahartikainen** [comment]
There are multiple errors (they come before the last one), and to fix them we would probably have to change code in Boost etc which is not really an option.

Could we switch to `clang-cl` toolchain? 

https://clang.llvm.org/docs/MSVCCompatibility.html

Appveyor should support it.

**Comment by bob-carpenter** [comment]
Usually these errors arise from a single line in Boost macros somewhere.  Ben Goodrich has tracked some down in the past and provided modified Boost files ahead of the release versions on the search path.  We haven't been doing that lately, but seeing all the bogus warnings is highly offputting to users.

**Comment by riddell-stan** [comment]
@ahartikainen do you have a sense of how to modify the branch so it works? Right now I'm mainly concerned with having some minimal testing on Windows to detect issues related to threading/multiprocessing if/when I manage to get parallel sampling working.

**Comment by ahartikainen** [comment]
@riddell-stan do you think this would be suitable format? (some parts of it)

https://github.com/touilleMan/godot-python/blob/master/appveyor.yml

**Comment by riddell-stan** [comment]
Whatever works is fine with me. The appveyor.yml in this branch/PR is taken from https://github.com/ogrisel/python-appveyor-demo . (The appveyor.yml and associated scripts may be unnecessarily complicated due to the need to support versions of Python before 3.6.)

I should look at your windows instructions before bothering you.

**Comment by ahartikainen** [comment]
Should we go with the mingw-w64 based build?

I kind of have one-liner for creating conda environment with right compiler etc. (Or maybe two lines?)

**Comment by riddell-stan** [comment]
@ahartikainen yes please! Feel also free to close this PR and open another if that's easier. The current setup might be overly complicated if we're just concerned with a simple check that things are working on Windows.

**Comment by ahartikainen** [comment]
Hi,

I was able to compile + run httpstan on windows with mingw-w64.

I made a branch that has the working components. There are parts that are needed to be fixed (for example makefile with python / python3). https://github.com/stan-dev/httpstan/tree/windows_fixes

Here are steps:

### Create conda environment

	conda create -n httpstan python=3.6 m2w64-toolchain libpython cython numpy pandas xarray matplotlib -c msys2 -c conda-forge
	conda activate httpstan

### pip install httpstan

	# install works, runnign is not working currently 
	pip install httpstan

### pip install from source

	# install works, windows_fixes branch works
	pip install grpcio-tools
	git clone https://github.com/stan-dev/httpstan
	cd httpstan
	pip install -r requirements.txt
	#pip install -r test-requirements.txt (if needed)
	mingw32-make.exe protos
	mingw32-make.exe cython
	pip install .
	#pip install -e . # for debugging (inplace)

**Comment by riddell-stan** [comment]
I can't seem to get conda installed on appveyor. I'm going to postpone working on this for awhile.

**Comment by ahartikainen** [comment]
Maybe we can use the setup from arviz?

**Pull request closed without merging**
