### PR TITLE
test: Verify a model with many parameters works

### PR DESCRIPTION
**Pull request by riddell-stan**
Check that a model with many parameters (160) works.
Prompted by a unusual bug in late 2020.

### CODE REVIEW

**Comment by riddell-stan** [comment]
- [ ] This test actually needs to be in pystan because the decoding issue was there. (Adding it here does no harm.)

**Comment by ahartikainen** [comment]
This test should make it sure that in fit_bytes has correct amount of parameters and they are in correct order. This is what failed in pystan, but is already in fit_bytes.

**Comment by riddell-stan** [comment]
Looks like the problem is with httpstan and the unix socket buffer size (on macOS). This test should be useful.

**Comment by riddell-stan** [comment]
This reproduces the error in https://github.com/stan-dev/pystan-next/issues/163. Test is appropriately failing.

**Pull request merged**
