### PR TITLE
Manual rollout for appveyor

### PR DESCRIPTION
**Pull request by ahartikainen**
Skip unnecessary commit -tests for PR with multiple untested commits.

### CODE REVIEW

**Comment by ahartikainen** [comment]
I rebased this PR with #179 so the tests could be run correctly.

**Comment by riddell-stan** [comment]
Can we see how bad things are with appveyor's "rollout builds" setting? I haven't had any problem so far. This adds a lot of confusing (to me) lines of code to the configuration.

**Comment by ahartikainen** [comment]
Yes, I think we could actually start with that. We need to change settings in appveyor. Maybe if we are not happy with the results, let's add this manual hack.

**Comment by ahartikainen** [comment]
I activated the rolling build option in appveyor (only for PR).

**Pull request closed without merging**
