### PR TITLE
docs: Correct log_prob and log_prob_grad docstring

### PR DESCRIPTION
**Pull request by mjcarter95**
Minor changes to the docstrings of log_prob and log_prob_grad.

### CODE REVIEW

**Comment by riddell-stan** [comment]
Just had a quick look. One note:

Perhaps something is missing? Maybe we need another test. If the user does not provide adjust_transform, does this not raise an exception?

If adjust_transform needs to be specified in Stan C++, we should require that it be given here.

**Comment by mjcarter95** [comment]
Hmm.. the schemas for `log_prob` and `log_prob_grad` should (theoretically) validate the request and set the default boolean parameters to true if they aren't specified by the user - this is why I changed required to false in the documents: should we base the docs on the behaviour of the Stan C++ method?

Also, I noticed an error in the `log_prob_grad` schema (doh!) we should validate `include_tparams` and `include_gqs`, not `adjust_transform`.

```
class ShowLogProbGradRequest(marshmallow.Schema):
    """Schema for log_prob_grad request."""

    data = fields.Nested(Data(), missing={})
    unconstrained_parameters = fields.List(fields.Float(), required=True)
    adjust_transform = fields.Boolean(missing=True)
```

**Comment by mjcarter95** [comment]
Hmm.. the schemas for `log_prob` and `log_prob_grad` should (theoretically) validate the request and set the default boolean parameters to true if they aren't specified by the user - this is why I changed required to false in the documents: should we base the docs on the behaviour of the Stan C++ method?

Additionally, is it worth adding a test when `adjust_transform` is true? We currently only test when this is false.

**Comment by riddell-stan** [comment]
@mjcarter95 I'm so sorry. I forgot that `missing` is marshmallow's way of specifying defaults. (I thought it implied that a missing field was allowed.)

No need to add a test, I think. This is a feature for expert users. I trust they'll report problems.

**Review by riddell-stan — APPROVED** [review]

**Pull request merged**
