### PR TITLE
fix: Remove unused code

### PR DESCRIPTION
**Pull request by riddell-stan**
Remove old Cython code which is no longer used.

### CODE REVIEW

**Comment by ahartikainen** [comment]
Do we need to add definition for 

    with importlib.resources.path(__package__, "stanc") as stanc_binary:

as 

    stanc_binary: pathlib.Path
    with importlib.resources.path(__package__, "stanc") as stanc_binary:

**Comment by riddell-stan** [comment]
That's something to consider. It's definitely a different issue though.

**Comment by riddell-stan** [comment]
This seems like a mypy bug. stanc_binary is interpreted as a Path.

**Comment by riddell-stan** [comment]
Trivial change. Merged without review.

**Pull request merged**
